### PR TITLE
Add meson build system support

### PR DESCRIPTION
**Pull request by mochaaP**
Working:

- Build as static/shared library
- Tests (You can update the list with some simple sh & grep.)
- Building `checkscoped`

To-dos:

- Benchmarks

### CODE REVIEW

**Comment by tylov** [comment]
Thanks a lot for this! Very useful, will look at it more soon.  The cmake build system will need an upgrade as well.

**Comment by tylov** [comment]
Works very well! Thanks again. Was nice to just install meson on windows with pip. Already had ninja.exe installed from the winlibs.com gcc/clang downloads.

**Comment by mochaaP** [comment]
Should I also add a CI test for meson? @tylov

**Comment by mochaaP** [comment]
Also, since this got merged, I will try to port the benchmark suite to meson :)

**Comment by tylov** [comment]
Hi, yes please do. I added 'default_library=both' to create both static and dynamically linked libs. Works great with gcc and clang both on windows (mingw64) and linux. However, with msvc (cl.exe), it does not create the stl.lib file. A convention with MSVC is to have stc.lib + stc.dll, and stc_s.lib as the static library.

**Comment by mochaaP** [comment]
> However, with msvc (cl.exe), it does not create the stl.lib file.

See <https://mesonbuild.com/FAQ.html#my-project-works-fine-on-linux-and-mingw-but-fails-to-link-with-msvc-due-to-a-missing-lib-file-fatal-error-lnk1181-why>; You might want to use `__declspec(dllexport)` or a `.def` file.

> A convention with MSVC is to have stc.lib + stc.dll, and stc_s.lib as the static library.

See <https://mesonbuild.com/Reference-manual_functions.html#library_name_suffix>; Meson writes to `libstc.a` instead to avoid name clash. You can override this behavior, but I don't recommend it.

**Comment by mochaaP** [comment]
@tylov I tested this on my local machine, works well with muon+tcc :) I think we can confidently remove CMakeLists.

**Comment by mochaaP** [comment]
when you're ready for a tagged release, @ me and I'll push this to meson's builtin package manager db.

**Pull request merged**
